[telegram.telegram_e]
# Create a bot according to instructions in https://github.com/42wim/matterbridge/wiki/Section-Telegram-%28basic%29
# Don't forget to set /setprivacy to disabled
# Create a group (not channel!) for forwarding, add the bot to it as an admin
Token="" # put your bot's Telegram token here
RemoteNickFormat="({PROTOCOL}) {NICK} "
MessageFormat="HTMLNick"
QuoteFormat="{MESSAGE} (re @{QUOTENICK}: {QUOTEMESSAGE})"
QuoteLengthLimit=46 # Truncuate long quotes to prevent spammy bridged messages
IgnoreMessages="^/" # Don't bridge bot commands (as the responses will not be bridged)


[whatsapp.whatsapp_e]
# Number you will use as a relay bot.
Number="+9xxxxxxxxx" # put your phone number here

# First time that you login you will need to scan QR code, then credentials will be saved in 
# a session file. 
# If you won't set SessionFile then you will need to scan QR code on every restart.
# optional (by default the session is stored only in memory, till restarting matterbridge)
SessionFile="/etc/matterbridge/whatsapp-session.gob"

# If your terminal is white we need to invert QR code in order for it to be scanned properly
# optional (default false)
QrOnWhiteTerminal=false

# Messages will be seen by other WhatsApp contacts as coming from the bridge. 
# Original nick will be part of the message.
RemoteNickFormat="[{PROTOCOL}] @{NICK}: "


# Just a test gateway from Telegram to Telegram to test your forwarding
[[gateway]]
name="test-gw"
enable=true
    [[gateway.in]]
    account="telegram.telegram_e"
    # For me the .in gateway worked only when prepending by -100 to the channel number from web.telegram.org
    channel="-1002101585638" 

    [[gateway.out]]
    account="telegram.telegram_e"
    # For the output or inout channel just use the number from web.telegram.org
    channel="-4073461884"

[[gateway]]
name="parents-hey"
enable=true

    [[gateway.in]]
    # See https://github.com/42wim/matterbridge/wiki/Section-WhatsApp-%28basic%29#how-to-set-the-wa-channel-in-the-configuration-file-of-matterbridge for instructions on how to find out the channel id for the desired inoput WhatsApp group or channel
    account="whatsapp.whatsapp_e"
    channel="972542181148-1567018938@g.us"

    [[gateway.out]]
    account="telegram.telegram_e"
    channel="-4073461884"

[tengo]
# Use for translation
OutMessage="/etc/matterbridge/trans.tengo"
